theme = "awesome-identity"
baseURL = "https://www.joshoberhaus.com"
title = "Josh Oberhaus - Software Engineer"
languageCode = "en-US"
# Content without language indicator will default to this language
defaultContentLanguage = "en"
# Make .Summary and .WordCount behave correctly for CJK languages
hasCJKLanguage = true
PygmentsCodeFences = true
# Enable to turn relative URLs into absolute
canonifyURLs = false
# Do not convert the url/path to lowercase
disablePathToLower = false
# Enable Emoji emoticons support for page content
enableEmoji = true
# Update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo = true
# Enable generation of `robots.txt` file
enableRobotsTXT = true


## Meta Configurations (HTTP Meta tags & OpenGraph)
[params.meta]
  description = "Technical Expert at Bosch."
  keywords = ""
  images = [
    "/images/profile.jpg"
  ]


## Profile Configurations
[params.profile]
  portrait = "/images/profile.jpg"
  firstname = "Josh"
  lastname = "Oberhaus"
  title = "Software Engineer"
  bio = """
  With nine years specializing in Driver Assistance, I bring expertise in Radar-based tracking and fusion, 
  alongside a diverse skill set from a total of 15 years in the automotive industry. 
  Committed to continual growth, I thrive on learning and empowering others in the field.
  
  Beyond my professional pursuits, I'm passionate about music as a saxophonist and find inspiration in outdoor adventures.  
  I am also a maker at heart, especially when it comes to projects relating to home automation.
  """


## Contacts Configurations
[params.contacts]
  email = "me@joshoberhaus.com"
  github = "joshOberhaus"
  linkedin = "joshoberhaus"


## Actions Configurations
[[params.actions]]
  name = "Review My Résumé"
  url = "https://raw.githubusercontent.com/joshOberhaus/Awesome-CV/master/project/JoshOberhausResume.pdf"


## Footer Configurations
[params.footer]
  poweredBy = true

## Privacy Configurations (GDPR)
[privacy]
  [privacy.googleAnalytics]
    disable = true
    # Make the users’ IP addresses are anonymized within Google Analytics
    anonymizeIP = true
    # Make the GA templates respect the “Do Not Track” HTTP header
    respectDoNotTrack = true